#!/usr/bin/env python

import json
import subprocess
import sys
import time

MAX_RETRIES = 20
RETRY_SLEEP = 1

def main():
  service = sys.argv[1]
  status  = sys.argv[2]
  checks = 0
  while True:
    checks += 1
    print 'Retry #%d...' % checks
    if get_status(service) == status:
      break
    if checks == MAX_RETRIES:
      print 'Timed out after %d retries' % MAX_RETRIES
      sys.exit(1);
    print 'Will retry in %d seconds' % RETRY_SLEEP
    time.sleep(RETRY_SLEEP)
  print 'Done!'


def get_status(service):
  output = subprocess.check_output(["docker-cloud", "service", "inspect", service])
  return json.loads(output)['state']

if __name__ == '__main__':
  main()
